# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  danak-app:
    image: danak
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://danak-mysql:3306/danak?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://danak-mysql:3306/danak?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    volumes:
      - /opt/asset:/opt/asset
    ports:
      - 8080:8080
    env_file:
      - /opt/asset/.env
  danak-mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'danak'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_ADMIN_USER}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
  asset:
