version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
    # uncomment for docker in docker
    privileged: true
    user: root
    container_name: jenkins
    volumes:
#     enable persistent volume (warning: make sure that the local jenkins_home folder is created)
    - ~/volumes/jenkins_home:/var/jenkins_home
#     mount docker sock and binary for docker in docker (only works on linux)
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
